#!/usr/bin/env bash
# One-shot installer for shixo-msn on Debian/Ubuntu (SysV init).
# Installs Go, fetches + builds the server, configures it, and starts it as
# a SysV service on 127.0.0.1:6303. Cloudflare Tunnel (or any front proxy)
# is expected to terminate TLS in front.
#
#   sudo bash provision.sh
#
# Idempotent: re-running updates code + rebuilds, and keeps the existing
# /etc/clip/config.toml untouched.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

APP=shixo-msn
DEPLOY_DIR=/opt/$APP
SVC_USER=jenkins                 # OS user that runs Jenkins (and the service)
PORT=6303
DATA_DIR=/var/lib/clip
CONFIG_DIR=/etc/clip
CONFIG_FILE=$CONFIG_DIR/config.toml
REPO=https://github.com/sherif-audibene/shixo-msn.git
GO_VERSION=1.23.4

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run as root:  sudo bash $0" >&2
  exit 1
fi
id "$SVC_USER" >/dev/null 2>&1 || { echo "User '$SVC_USER' not found. Install Jenkins first."; exit 1; }

echo "==> [1/6] System packages (git, curl, openssl, ca-certs)"
apt-get update -y
apt-get install -y ca-certificates curl git openssl rsync

echo "==> [2/6] Go ${GO_VERSION}"
NEED_GO=1
if command -v go >/dev/null 2>&1; then
  CUR=$(go version | awk '{print $3}' | sed 's/^go//')
  # accept any 1.23+ version
  MAJ=$(echo "$CUR" | cut -d. -f1)
  MIN=$(echo "$CUR" | cut -d. -f2)
  if [ "$MAJ" = "1" ] && [ "$MIN" -ge 23 ]; then NEED_GO=0; fi
fi
if [ "$NEED_GO" = 1 ]; then
  ARCH=$(dpkg --print-architecture)   # amd64 / arm64
  TGZ=/tmp/go${GO_VERSION}.tgz
  curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz" -o "$TGZ"
  rm -rf /usr/local/go
  tar -C /usr/local -xzf "$TGZ"
  ln -sf /usr/local/go/bin/go     /usr/local/bin/go
  ln -sf /usr/local/go/bin/gofmt  /usr/local/bin/gofmt
  rm -f "$TGZ"
fi
echo "    go $(go version | awk '{print $3}')"

echo "==> [3/6] Source code at $DEPLOY_DIR"
git config --global --add safe.directory "$DEPLOY_DIR" 2>/dev/null || true
if [ -d "$DEPLOY_DIR/.git" ]; then
  git -C "$DEPLOY_DIR" fetch --depth 1 origin main
  git -C "$DEPLOY_DIR" reset --hard origin/main
else
  mkdir -p "$DEPLOY_DIR"
  git clone --depth 1 "$REPO" "$DEPLOY_DIR"
fi

echo "==> [4/6] Configuration ($CONFIG_FILE)"
mkdir -p "$CONFIG_DIR"
if [ -f "$CONFIG_FILE" ]; then
  echo "    Exists — leaving it as-is."
else
  TOKEN=$(openssl rand -base64 48 | tr -d '\n' | tr '/+' '_-')
  umask 077
  cat > "$CONFIG_FILE" <<EOF
# /etc/clip/config.toml — generated by provision.sh
listen   = "127.0.0.1:$PORT"
data_dir = "$DATA_DIR"
token    = "$TOKEN"
tls_cert = ""
tls_key  = ""
EOF
  chmod 640 "$CONFIG_FILE"
  chown root:"$SVC_USER" "$CONFIG_FILE"
  echo
  echo "    >>> Generated bearer token (paste into each client's ~/.clip/config.toml):"
  echo "        $TOKEN"
  echo
fi

mkdir -p "$DATA_DIR"
chown -R "$SVC_USER:$SVC_USER" "$DATA_DIR"

echo "==> [5/6] Build clipsrv"
cd "$DEPLOY_DIR"
# Build as $SVC_USER so caches land in its homedir and Jenkins rebuilds reuse them.
# Let the jenkins user trust this repo (its files are owned by jenkins after
# the chown below, but git's dubious-ownership check still trips when the
# checkout was created by root).
git config --global --add safe.directory "$DEPLOY_DIR" 2>/dev/null || true
sudo -u "$SVC_USER" git config --global --add safe.directory "$DEPLOY_DIR" 2>/dev/null || true
chown -R "$SVC_USER:$SVC_USER" "$DEPLOY_DIR"

sudo -u "$SVC_USER" -H bash -c "
  set -e
  cd '$DEPLOY_DIR'
  export CGO_ENABLED=0 GOFLAGS=-trimpath
  go build -buildvcs=false -ldflags='-s -w' -o '$DEPLOY_DIR/clipsrv' ./cmd/clipsrv
"

echo "==> [6/6] SysV service + Jenkins sudoers"
LOG=/var/log/$APP.log
touch "$LOG"; chown "$SVC_USER" "$LOG"

install -m 0755 "$DEPLOY_DIR/deploy/init.d/$APP" /etc/init.d/$APP

command -v update-rc.d >/dev/null 2>&1 && update-rc.d "$APP" defaults >/dev/null 2>&1 || true
service "$APP" restart || /etc/init.d/$APP restart

# Let Jenkins restart the service after every deploy, no password.
cat > /etc/sudoers.d/$APP <<EOF
$SVC_USER ALL=(root) NOPASSWD: /usr/sbin/service $APP restart, /usr/sbin/service $APP status
EOF
chmod 440 /etc/sudoers.d/$APP

echo
echo "==> Health check"
ok=0
for _ in $(seq 1 30); do
  if [ "$(curl -fsS http://127.0.0.1:$PORT/api/health 2>/dev/null)" = "ok" ]; then ok=1; break; fi
  sleep 1
done
if [ "$ok" = 1 ]; then
  echo "✅ Running on http://127.0.0.1:$PORT/"
else
  echo "⚠️  Service started but health check did not pass. Check: tail -n 50 $LOG"
fi
echo
echo "Next:"
echo "  • Add a Cloudflare Tunnel ingress mapping your hostname -> http://localhost:$PORT"
echo "  • Future deploys: push to GitHub, Jenkins job '$APP' will rebuild + restart"
echo "  • Manage:  sudo service $APP {start|stop|restart|status}"
echo "  • Edit config:  sudoedit $CONFIG_FILE && sudo service $APP restart"
